name: bein-streaming
services:
  - name: streaming
    type: web
    ports:
      - port: 8080
        http_path: /health
    docker:
      image: yourusername/bein-streaming:latest
    scaling:
      min: 1
      max: 3
    healthcheck:
      http:
        path: /health
        port: 8080
        initial_delay_seconds: 30
        period_seconds: 15
