name: bein-iptv-proxy
services:
  - name: proxy
    type: web
    ports:
      - port: 8080
        http_path: /health
    docker:
      image: yourusername/bein-iptv-proxy:latest
    env:
      - name: TZ
        value: UTC
    scaling:
      min: 1
      max: 3
    healthcheck:
      http:
        path: /health
        port: 8080
        initial_delay_seconds: 30
        period_seconds: 15
