name: bein-iptv-hidden
app:
  name: bein-hidden-proxy
  regions: ["fra", "iad", "sin", "nyc"]
  
services:
  - name: proxy
    type: web
    ports:
      - port: 8080
        http_path: /health
    docker:
      image: yourusername/bein-hidden-proxy:latest
    env:
      - name: TZ
        value: UTC
      - name: NGINX_ENVSUBST_OUTPUT_DIR
        value: /etc/nginx
    scaling:
      min: 2
      max: 5
      target_cpu_utilization: 70
    healthcheck:
      http:
        path: /health
        port: 8080
        initial_delay_seconds: 30
        period_seconds: 15
        timeout_seconds: 10
        success_threshold: 1
        failure_threshold: 3
    resources:
      instance_types:
        - micro
      cpu: [250, 1000]
      memory: [512, 2048]
    volumes:
      - path: /tmp/nginx-cache
        size_gib: 3
