name: iptv-proxy
services:
  - name: nginx-proxy
    docker:
      image: yourusername/iptv-proxy:latest
    ports:
      - port: 8080
        http_path: /health
    env:
      - name: TZ
        value: UTC
    regions:
      - fra  # Frankfurt
      - iad  # Washington DC
      - sin  # Singapore
    scaling:
      min: 2
      max: 5
    health_checks:
      http:
        path: /health
        port: 8080
        initial_delay_seconds: 30
        period_seconds: 15
