version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: iptv-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "1935:1935"  # For HLS output
    environment:
      - TZ=UTC
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cache:/tmp/nginx-cache
      - ./channels.m3u:/etc/nginx/channels.m3u:ro
    networks:
      - iptv-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Simple web interface to list channels
  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    depends_on:
      - nginx

networks:
  iptv-net:
    driver: bridge
